#ifndef TIMER1_CONFIG
#define TIMER1_CONFIG


#define TIMER1_WAVEFORM_GENERATION_MODE      (TIMER1_NORMAL)

#define TIMER1_INTERRUPT_MODE                (TIMER1_ACTIVATE_INT_MODE)

#define TIMER1_INPUT_CAPTURE_MODE              (TIMER1_ICU_FALLING_EDGE)

#define TIMER1_INPUT_CAPTURE_INTERRUPT_MODE   (TIMER1_ACTIVATE_ICU_INTERRUPT)

#define TIMER1_CLOCK_SELECTION                  (TIMER1_PS_1024)



#endif