#ifndef HEXADECODER_CONFIG_FILE
#define HEXADECODER_CONFIG_FILE


// Hexadecoder Pins Groups
#define HEXADECODER_A_GROUP     DIO_PIN_GROUP_A
#define HEXADECODER_B_GROUP     DIO_PIN_GROUP_A 
#define HEXADECODER_C_GROUP     DIO_PIN_GROUP_A
#define HEXADECODER_D_GROUP     DIO_PIN_GROUP_A
#define HEXADECODER_EN1_GROUP   DIO_PIN_GROUP_B
#define HEXADECODER_EN2_GROUP   DIO_PIN_GROUP_B
#define HEXADECODER_DP_GROUP    DIO_PIN_GROUP_B

// Hexadecoder Pins Numbers
#define HEXADECODER_A_PIN     DIO_PIN_4
#define HEXADECODER_B_PIN     DIO_PIN_5
#define HEXADECODER_C_PIN     DIO_PIN_6
#define HEXADECODER_D_PIN     DIO_PIN_7
#define HEXADECODER_EN1_PIN   DIO_PIN_2
#define HEXADECODER_EN2_PIN   DIO_PIN_1
#define HEXADECODER_DP_PIN    DIO_PIN_3

//SSGs Numbering From left to write 
#define SSG_1     0   //Eng1
#define SSG_2     1   //Eng2
//#define SSG_N   N-1 //ENG(N-1)


#endif