#ifndef ADC_CONFIG_FILE
#define ADC_CONFIG_FILE


//Options: ADC_AREF, ADC_AVCC, and ADC_INTERNAL 
#define ADC_V_REFERENCE_SOURCE  ADC_AVCC

//Options: ADC_LEFT_ADJUSTED and ADC_RIGHT_ADJUSTED
#define ADC_DATA_ADJUSTMENT  ADC_LEFT_ADJUSTED

//Options: ADC_SINGLE_CONVERSION_MODE and  ADC_AUTO_TRIGGERED_MODE 

/*
    Options:
    ADC_SINGLE_CONVERSION
    ADC_FREE_RUNNING
    ADC_ANALOG_COMPARATOR
    ADC_EXTERNL_INT0
    ADC_TIMER0_COMPARE_MATCH
    ADC_TIMER0_OVERFLOW
    ADC_TIMER_COMPARE_MATCH_B
    ADC_TIMER1_OVERFLOW
    ADC_TIMER1_CAPTURE_EVENT
*/
#define ADC_TRIGGER_SOURCE  ADC_FREE_RUNNING


//Options: ADC_INT_ENABLE   ADC_INT_DISABLE
#define ADC_INT_EVENT_STATUS  ADC_INT_ENABLE

//Options:  ADC_PS_2, ADC_PS_4, ADC_PS_8, ADC_PS_16, ADC_PS_32, ADC_PS_64, and ADC_PS_128 
#define ADC_PS_FACTOR  ADC_PS_64


/*
    Options:
    Single Ended:         
                 
    ADC_ADC0
    ADC_ADC1
    ADC_ADC2
    ADC_ADC3
    ADC_ADC4
    ADC_ADC5
    ADC_ADC6
    ADC_ADC7

    Differential:
    ADC_ADC0_ADC0_10x 
    ADC_ADC1_ADC0_10x 
    ADC_ADC0_ADC0_200x
    ADC_ADC1_ADC0_200x

    ADC_ADC2_ADC2_10x  
    ADC_ADC3_ADC2_10x  
    ADC_ADC2_ADC2_200x 
    ADC_ADC3_ADC2_200x 

    ADC_ADC0_ADC1_1x 
    ADC_ADC1_ADC1_1x 
    ADC_ADC2_ADC1_1x 
    ADC_ADC3_ADC1_1x 
    ADC_ADC4_ADC1_1x 
    ADC_ADC5_ADC1_1x 
    ADC_ADC6_ADC1_1x 
    ADC_ADC7_ADC1_1x 
    ADC_ADC0_ADC2_1x 
    ADC_ADC1_ADC2_1x 
    ADC_ADC2_ADC2_1x 
    ADC_ADC3_ADC2_1x 
    ADC_ADC4_ADC2_1x 
    ADC_ADC5_ADC2_1x 

    Testing (Single Ended):
    ADC_V_BG  
    ADC_V_GND 

*/ 
#define ADC_INPUT_CHANNEL ADC_ADC0


#endif